sistema/produto/urls.py
from .views import *
from django.urls import path


urlpatterns = [
    path('', ProductIndex.as_view(), name='index'),
    path('produto/listar/', ProductList.as_view(), name='all_products'),
    path('produto/listar/dash', ProductListDash.as_view(), name='dash_products'),
    path('produto/<int:product_id>', Product_Single.as_view(), name='product_single'),
    path('produto/criar/', CreateProduct.as_view(), name='create_product'),
    path('produto/editar/<int:pk>', UpdateProduct.as_view(), name='update_product'),
    path('produto/deletar/', DeleteProduct.as_view(), name='delete_product'),
    path('criar/comentario/produto/<int:product_id>/<int:user_id>', CreateCommentProduct.as_view(), name='comment_product'),
    path('deletar/comentario/produto/', DeleteCommentProduct.as_view(), name='delete_comment_product'),
    path('atualizar/comentario/produto/', UpdateCommentProduct.as_view(), name='update_comment_product'),
    path('mural/', CommentPageList.as_view(), name='mural_comment'),
    path('criar/comentario/page/<int:user_id>', CreateCommentPage.as_view(), name='create_comment_page'),
    path('deletar/comentario/page/', DeleteCommentPage.as_view(), name='delete_comment_page'),
    path('atualizar/comentario/page/', UpdateCommentPage.as_view(), name='update_comment_page'),  
    
]

sistema/produto/models.py
from django.db import models
from users.models import User
from tipo.models import Type
from colecao.models import Collection
from parametros.models import Parameters
from django.db.models import Count

# Create your models here.

    
class Product(models.Model):
    name = models.CharField(max_length=100)
    description = models.TextField()
    type = models.ForeignKey(Type, on_delete=models.CASCADE)
    collection = models.ForeignKey(Collection, on_delete=models.CASCADE)
    path = models.ImageField(upload_to='img/%Y/%m/%d/')

    def __str__(self):
        return self.name
    
    def user_commented(self, user):
        return CommentPage.objects.filter(id_user=user).exists()
    
    def most_commented(self):
       return self.objects.annotate(comment_count=Count('comment')).order_by('-comment_count')[:10]
    
    def product_commented(self, user):
        return CommentProduct.objects.filter(id_product=self, id_user=user).exists()
    
    def get_price(self):
        try:
            # Obter o primeiro ProductCost relacionado ao produto
            product_cost = self.productcost_set.first()  # Ajuste o critério se necessário
            if product_cost:
                return product_cost.get_price()
            else:
                return 0
        except ProductCost.DoesNotExist:
            return 0

class ProductCost(models.Model):
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    parameters = models.ForeignKey(Parameters, on_delete=models.CASCADE)
    raw_materials = models.DecimalField(max_digits=8, decimal_places=2)
    labor = models.DecimalField(max_digits=8, decimal_places=2)
    indirect = models.DecimalField(max_digits=8, decimal_places=2)

    def get_price_cost(self):
        return (self.raw_materials + self.labor + self.indirect)
    
    def get_price(self):
        cost = self.get_price_cost()
        divisor = self.parameters.get_divisor()
        if divisor == 0:
            raise ValueError("Divisor cannot be zero.")
        return cost / divisor

class CommentProduct(models.Model):
    id_product = models.ForeignKey(Product, on_delete=models.CASCADE)
    id_user = models.ForeignKey(User, on_delete=models.CASCADE)
    comment = models.TextField()

    def __str__(self):
        return f'{self.id_user} on {self.id_product}'

class CommentPage(models.Model):
    id_user = models.ForeignKey(User, on_delete=models.CASCADE)
    comment = models.TextField()

    def __str__(self):
        return self.comment

sistema/produto/templates/produto/partials/_edit_comment_page.html
<div class="modal fade" id="comment-page-{{ comment.id }}" tabindex="-1" aria-labelledby="editcommentpage{{comment.id}}" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content px-4">
            <div class="modal-header">
                <h5 class="modal-title" id="editcommentpage{{comment.id}}">Editar Comentario do Produto</h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <form method="post" action="{% url 'update_comment_page'  %}">
                {% csrf_token %}
                <input type="hidden" name="comment_id" value="{{ comment.id }}">
                <input type="hidden" name="user_id" value="{{ request.user.id }}">
                
                <div class="mb-3">
                    <label for="id_comment" class="form-label">Comentário</label>
                    <textarea name="comment" class="form-control" id="id_comment" required>{{ comment.comment }}</textarea>
                </div>
                
                <div class="modal-footer d-flex justify-content-center">
                    <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Cancelar</button>
                    
                    <button type="submit" class="btn btn-primary">Salvar</button>
                </div>
            </form>
        </div>
    </div>
</div>

sistema/produto/templates/produto/partials/_edit_comment_product.html
<div class="modal fade" id="comment-product-{{ comment.id }}" tabindex="-1" aria-labelledby="editcommentproduct{{comment.id}}" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content px-4">
            <div class="modal-header">
                <h5 class="modal-title" id="editcommentproduct{{comment.id}}">Editar Comentario do Produto</h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <form method="post" action="{% url 'update_comment_product'  %}">
                {% csrf_token %}
                <input type="hidden" name="comment_id" value="{{ comment.id }}">
                <input type="hidden" name="product_id" value="{{ product.id }}">
                <input type="hidden" name="user_id" value="{{ request.user.id }}">
                
                <div class="mb-3">
                    <label for="id_comment" class="form-label">Comentário</label>
                    <textarea name="comment" class="form-control" id="id_comment" required>{{ comment.comment }}</textarea>
                </div>
                
                <div class="modal-footer d-flex justify-content-center">
                    <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Cancelar</button>
                    
                    <button type="submit" class="btn btn-primary">Salvar</button>
                </div>
            </form>
        </div>
    </div>
</div>