sistema/colecao/urls.py
from django.urls import path
from .views import *

urlpatterns = [
    path('<int:id>/',CollectionDetailView.as_view() , name='collection_detail'),
    path('criar/',CollectionCreateView.as_view() , name='collection_create'),#ok
    path('deletar/<int:id>/',CollectionDeleteView.as_view() , name='collection_delete'),#ok
    path('update/<int:id>/',CollectionUpdateView.as_view() , name='collection_update'),#ok
    path('listar/',CollectionListView.as_view() , name='collection_list'),#ok
    path('listar/dash',CollectionListDashView.as_view() , name='collection_dash'),#ok
    
]

sistema/colecao/models.py
from django.db import models
from users.models import User

# Create your models here.
class Collection(models.Model):
    name = models.CharField(max_length=100)
    description = models.TextField(max_length=200)
    image = models.ImageField(upload_to='img/%Y/%m/%d/')

    def __str__(self):
        return self.name

sistema/colecao/views.py
from django.views import View
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib import messages  
from .repository import CollectionRepository
from .forms import CollectionForm
from django.utils.decorators import method_decorator
from users.decorators import *
from django.contrib.auth.decorators import login_required
from .service import CollectionService
from produto.service import ProductService
from users.forms import *


class CollectionListView(View):
    template_name = 'colecao/collections.html'
    paginate_by = 10
    form_login = EmailLoginForm
    form_register = UserForm

 
    def get(self, request, *args, **kwargs):
        page = request.GET.get('page', 1)
        per_page = self.paginate_by
        
        collections = CollectionService.list_all_collections(page=page, per_page=per_page)
        
        return render(request, self.template_name, {'collections': collections, 'form_login': self.form_login, 'form_register': self.form_register})
       

class CollectionDetailView(View):
    template_name = 'colecao/collection_single.html'
    form_login = EmailLoginForm
    form_register = UserForm

    def get(self, request, id, *args, **kwargs):
    
        collection = CollectionService.get_collection_by_id(id)
        products = ProductService.get_products_by_collection(id_collection=id)
        return render(request, self.template_name, {'collection':collection, 'products':products, 'form_login': self.form_login, 'form_register': self.form_register})


@method_decorator(user_is_manager, name='dispatch')
class CollectionCreateView(View):

    def get(self, request):
        form_collection = CollectionForm()
        return render(request, 'colecao/criar_colecao.html', {'form_collection': form_collection})

    def post(self, request, *args, **kwargs):
        form = CollectionForm(request.POST, request.FILES)
        if form.is_valid():
            # Chamando o serviço com os dados corretos
            CollectionService.create_collection(
                name=form.cleaned_data['name'],
                description=form.cleaned_data['description'],
                image=form.cleaned_data['image']
            )
            messages.success(request, "Coleção criada com sucesso!")
            return redirect('collection_list')
        else:
            messages.error(request, "Erro ao criar a coleção.")
            return redirect('collection_list')


@method_decorator(user_is_manager, name='dispatch')
class CollectionDeleteView(View):
   
    def post(self, request, id, *args, **kwargs):
        success = CollectionService.delete_collection(id)
        if success:
            messages.success(request, 'Coleção deletada com sucesso!')
        else:
            messages.error(request, 'Erro ao deletar a coleção.')
        return redirect('collection_dash')
    

@method_decorator(user_is_manager, name='dispatch')
class CollectionUpdateView(View):

    def post(self, request, id, *args, **kwargs):
        name = request.POST.get('name')
        description = request.POST.get('description')
        success = CollectionRepository.update_collection(id, name, description, request.FILES.get('image'))
        if success:
            messages.success(request, 'Coleção atualizada com sucesso!')
        else:
            messages.error(request, 'Erro ao atualizar a coleção.')
        return redirect('collection_dash')
    
    def get(self, request, id):
        collection = CollectionService.get_collection_by_id(id)
        form_collection = CollectionForm(collection)
        return

@method_decorator(user_is_manager, name='dispatch')
class CollectionListDashView(View):

    def get(self, request):
        form_collection = CollectionForm
        collections = CollectionService.list_all_collections()
        return render(request, 'colecao/collections_dash.html', {'collections': collections, 'form_collection': form_collection})

sistema/colecao/templates/colecao/collection_single.html
{% extends 'users/base.html' %}
{% load static %}

{% block title %}
    <title>Detalhaes da Coleção</title>
{% endblock %}

{% block style %}
    <link rel="apple-touch-icon" href="{% static 'assets/img/apple-icon.png' %}">
    <link rel="shortcut icon" type="image/x-icon" href="{% static 'assets/img/favicon.ico' %}">
    <link rel="stylesheet" href="{% static 'assets/css/templatemo.css' %}">

    <!-- Load fonts style after rendering the layout styles -->
    <link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Roboto:wght@100;200;300;400;500;700;900&display=swap'">
    <link rel="stylesheet" href="{% static 'assets/css/fontawesome.min.css' %}">

    <!-- Slick -->
    <link rel="stylesheet" type="text/css" href="{% static 'assets/css/slick.min.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'assets/css/slick-theme.css' %}">
{% endblock %}    

{% block content %}
    <!-- Open Content -->
    <section>
        <div class="container pb-5">
            <div class="row">
                {% if collection.image %}
                <div class="col-lg-5 mt-5">
                    <div class="card mb-3">
                        <img class="card-img img-fluid" src="{{collection.image.url}}" alt="Card image cap" id="collection-detail">
                    </div>
                </div>
                {% endif %}
                <!-- col end -->
                <div class="col-lg-7 mt-5">
                    <div class="card">
                        <div class="card-body">
                            <h1 class="h2">{{collection.name}}</h1>
                            <h6>Descrição:</h6>
                            <p>{{collection.description}}</p>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
    <section>
        <div class="text-center">
            <h3>Produtos Relacionados</h3>
        </div>
        <div class="container">
            <div class="row">
                {% for product in products %}
                <div class="col-12 col-sm-6 col-md-4 col-lg-3 mb-4">
                    <a href="{% url 'product_single' product.id %}" style="text-decoration:none; color: black;">
                    <div class="card" style="width: 18rem; display: flex; flex-direction: column; height: 500px;">
                      <div class="card-img-container" style="height: 350px; overflow: hidden;">
                        <img src="{{ product.path.url }}" class="card-img-top" alt="{{ product.name }}" style="width: 100%; height: 100%; object-fit: cover;">
                      </div>
                      <div class="card-body text-center" style="flex-grow: 1; display: flex; flex-direction: column; justify-content: space-between;">
                        <h5 class="card-title">{{ product.name }}</h5>
                        <hr style="margin: 2px 0;">
                        <p class="text-center" style="font-size: 16px; margin: 10px 0;">Descrição: {{ product.description }}</p>
                      </div>
                    </div>
                  </a>
                </div>
                {% endfor %}
              </div>
        </div>
        
    </section>
   
{% endblock %}

sistema/colecao/templates/colecao/collections.html
{% extends 'users/base.html' %}
{% load static %}

{% block title %}
<title>Coleções</title>
{% endblock %}

{% block style %}
<style>
  .title {
    text-align: center;
    font-size: 36px;
    font-weight: bold;
    margin-bottom: 20px;
  }

  .card {
    margin: 10px;
  }

  .btn-group {
    width: 300px;
    height: 100px;
    margin-top: 40px;
  }
</style>
{% endblock %}

{% block content %}
<section>

  <div class="d-flex justify-content-center">
    <div class="pt-5">
      <h1>Coleções</h1>
    </div>
  </div>

  <div class="container">
    <div class="d-flex row justify-content-center">
      {% for collection in collections %}
      {% if collection.image %}
      <div class="col-12 col-sm-6 col-md-6 col-lg-3 py-2">
        <a href="{% url 'collection_detail' collection.id %}" style="text-decoration: none; color: black;">
        <div class="card" style="height: 400px;">
          <div class="card-body d-flex row">
            <div class="d-flex justify-content-center">
              <img src="{{ collection.image.url }}" alt="" width="150px" height="150px" style="border-radius: 50%;">
            </div>
            <div>
              <h5 class="card-title text-center display-7" style="font-size: 24px;">{{collection.name}}</h5>
              <hr style="margin: 2px 0px 2px 0px;">
              <p class="card-text text-center " style="font-size: 18px;">{{collection.description}}</p>
            </div>
          </div>
        </div>
        </a>
      </div>
      {% endif %}
      {% endfor %}
    </div>
    <nav aria-label="Page navigation example">
      <ul class="pagination d-flex justify-content-center">
          {% if collections.has_previous %}
              <li class="page-item"><a class="page-link" href="?page={{ collections.previous_page_number }}">Anterior</a></li>
              <li class="page-item"><a class="page-link" href="?page=1">1</a></li>
          {% endif %}
          <li class="page-item active"><a class="page-link" href="#">{{ collections.number }}</a></li>
          {% if collections.has_next %}
              <li class="page-item"><a class="page-link" href="?page={{ collections.paginator.num_pages }}">{{ collections.paginator.num_pages }}</a></li>
              <li class="page-item"><a class="page-link" href="?page={{ collections.next_page_number }}">Próxima</a></li>
          {% endif %}
      </ul>
  </nav>  
  </div>
</section>
{% endblock %}

sistema/colecao/templates/colecao/collections_dash.html
{% extends 'users/base.html' %}
{% load static %}

{% block title %}
<title>Dashboard Coleção</title>
{% endblock %}

{% block style %}
<style>
  .card {
    margin: 10px;
  }

  .btn-group {
    width: 300px;
    height: 100px;
    margin-top: 40px;
  }
</style>
{% endblock %}

{% block content %}
<section class="py-5">

  <div class="d-flex justify-content-center">
    <div class="texr-center">
      <h1>Coleção</h1>
    </div>
    <div class="position-absolute end-0">
      <button type="button"  class="btn" >
        <a href="{% url 'collection_create' %}">
        <svg xmlns="http://www.w3.org/2000/svg" width="30" height="30" fill="blue" class="bi bi-plus-square-fill" viewBox="0 0 16 16">
          <path d="M2 0a2 2 0 0 0-2 2v12a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2V2a2 2 0 0 0-2-2zm6.5 4.5v3h3a.5.5 0 0 1 0 1h-3v3a.5.5 0 0 1-1 0v-3h-3a.5.5 0 0 1 0-1h3v-3a.5.5 0 0 1 1 0"/>
        </svg>
        </a>
      </button>
    </div>
  </div>

  <div class="container">
    <div class="row">
      {% for collection in collections %}
      {% if collection.image %}
      <div class="col-sm-4 mb-3 mb-sm-0 pb-3">
        <div class="card border-2">
          <div class="card-body text-end">
            <span class="badge text-bg-secondary"># {{collection.id}}</span>
            <p class="f text-start mb-1" style="font-size: 12px; color: dimgray;">Coleção:</p>
            <h5 class="card-title text-start">{{collection.name}}</h5>
            <hr>
            <p class="f text-start mb-1" style="font-size: 12px; color: dimgray;">{{collection.description}}</p>
            <hr>
            <div class="d-flex justify-content-center">
              <img src="{{collection.image.url}}" height="60px" width="60px" alt="">
            </div>
            <hr>
            <p class="f text-start mb-1" style="font-size: 12px; color: dimgray;">Ações:</p>
            <a href="#" data-bs-toggle="modal" data-bs-target="#collection-{{collection.id}}" class="btn edit-collection-btn" data-collection-id="{{ collection.id }}" data-collection-name="{{ collection.name }}">
              <svg xmlns="http://www.w3.org/2000/svg" width="22" height="22" fill="blue" class="bi bi-pencil-square" viewBox="0 0 16 16">
                  <path d="M15.502 1.94a.5.5 0 0 1 0 .706L14.459 3.69l-2-2L13.502.646a.5.5 0 0 1 .707 0l1.293 1.293zm-1.75 2.456-2-2L4.939 9.21a.5.5 0 0 0-.121.196l-.805 2.414a.25.25 0 0 0 .316.316l2.414-.805a.5.5 0 0 0 .196-.12l6.813-6.814z"/>
                  <path fill-rule="evenodd" d="M1 13.5A1.5 1.5 0 0 0 2.5 15h11a1.5 1.5 0 0 0 1.5-1.5v-6a.5.5 0 0 0-1 0v6a.5.5 0 0 1-.5.5h-11a.5.5 0 0 1-.5-.5v-11a.5.5 0 0 1 .5-.5H9a.5.5 0 0 0 0-1H2.5A1.5 1.5 0 0 0 1 2.5z"/>
              </svg>
            </a>
            <form method="post" action="{% url 'collection_delete' collection.id %}" style="display:inline;">
              {% csrf_token %}
              <button type="submit" style="background-color: transparent; border: none;">
              <a href="#" class="btn delete-collection-btn" data-collection-id="{{ collection.id }}">
                <svg xmlns="http://www.w3.org/2000/svg" width="22" height="22" fill="red" class="bi bi-trash3-fill" viewBox="0 0 16 16">
                    <path d="M11 1.5v1h3.5a.5.5 0 0 1 0 1h-.538l-.853 10.66A2 2 0 0 1 11.115 16h-6.23a2 2 0 0 1-1.994-1.84L2.038 3.5H1.5a.5.5 0 0 1 0-1H5v-1A1.5 1.5 0 0 1 6.5 0h3A1.5 1.5 0 0 1 11 1.5m-5 0v1h4v-1a.5.5 0 0 0-.5-.5h-3a.5.5 0 0 0-.5.5M4.5 5.029l.5 8.5a.5.5 0 1 0 .998-.06l-.5-8.5a.5.5 0 1 0-.998.06m6.53-.528a.5.5 0 0 0-.528.47l-.5 8.5a.5.5 0 0 0 .998.058l.5-8.5a.5.5 0 0 0-.47-.528M8 4.5a.5.5 0 0 0-.5.5v8.5a.5.5 0 0 0 1 0V5a.5.5 0 0 0-.5-.5"/>
                </svg>
              </a>
              </button>
            </form>
          </div>
        </div>
    </div>
    {% include 'colecao/partials/_edit_collection.html' %}
    {% endif %}
      {% endfor %}
    </div>
    <nav aria-label="Page navigation example">
      <ul class="pagination d-flex justify-content-center">
          {% if collections.has_previous %}
              <li class="page-item"><a class="page-link" href="?page={{ collections.previous_page_number }}">Anterior</a></li>
              <li class="page-item"><a class="page-link" href="?page=1">1</a></li>
          {% endif %}
          <li class="page-item active"><a class="page-link" href="#">{{ collections.number }}</a></li>
          {% if collections.has_next %}
              <li class="page-item"><a class="page-link" href="?page={{ collections.paginator.num_pages }}">{{ collections.paginator.num_pages }}</a></li>
              <li class="page-item"><a class="page-link" href="?page={{ collections.next_page_number }}">Próxima</a></li>
          {% endif %}
      </ul>
  </nav>  
  </div>
</section>
<!-- 
<script>
  document.addEventListener("DOMContentLoaded", function() {
      var deleteButtons = document.querySelectorAll('.delete-collection-btn');
      deleteButtons.forEach(function(button) {
          button.addEventListener('click', function() {
              var collectionId = this.getAttribute('data-collection-id');
              var confirmation = confirm("Você tem certeza que deseja deletar esta coleção?");
              if (confirmation) {
                  window.location.href = '/colecao/deletar/' + collectionId + '/';
              }
          });
      });
  });
</script> -->

{% endblock %}

sistema/colecao/templates/colecao/criar_colecao.html
{% extends 'users/base.html' %}
{% load static %}

{% block title %}
    <title>Criar Coleção</title>
{% endblock %}

{% block style %}
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    <style>
      .custom-form {
        background-color: #eef7ff;
        padding: 20px;
        border-radius: 25px;
        max-width: 1000px;
        width: 90%;
        margin: 50px auto;
      }

      .custom-button {
        background-color: #00b7ff;
        border-radius: 25px;
        color: white;
        border: none;
        padding: 10px 30px;
        font-weight: bold;
      }

      .form-group {
        display: flex;
        align-items: center;
        margin-bottom: 20px;
      }

      .form-label {
        flex: 0 0 150px;
        padding-right: 10px;
      }

      .form-control {
        flex: 1; 
      }

      @media (max-width: 768px) {
        .custom-form {
          width: 95%;
          padding: 15px;
          margin: 20px auto;
        }

        .custom-button {
          width: 100%;
          padding: 10px;
        }

        .form-group {
          flex-direction: column;
          align-items: flex-start;
        }

        .form-label {
          flex: none;
          padding-right: 0;
          margin-bottom: 5px;
        }

        .form-control {
          width: 100%; 
        }
      }
    </style>
{% endblock %}

{% block content %}
  <div class="py-5">
    <h1 class="text-center">Criar Coleção</h1>
  </div>    
    <div class="modal-body pb-5">
      <div class="container" style="width: 80%;">
        <div class="p-5" style="background-color: #eef7ff; color:black; border-radius: 10px;">
            <form method="post" class="" action="{% url 'collection_create' %}" enctype="multipart/form-data">
                {% csrf_token %}
                {{ form_collection.as_p }}
                <div class="text-center py-3">
                  <button type="submit" style="border-radius: 7px; background-color: #00b7ff; color: white; text-align: center;" class="btn">Cadastrar</button>
                </form>
                <button type="button" class="btn btn-secondary"  data-bs-dismiss="modal">Cancelar</button>
              </div>
        </div>
      </div>
      
    </div>

{% endblock %}

sistema/colecao/templates/colecao/partials/_edit_collection.html
<div class="modal fade" id="collection-{{collection.id}}" tabindex="-1" aria-labelledby="editCollection{{collection.id}}" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content px-4">
            <div class="modal-header">
                <h5 class="modal-title" id="editCollection{{collection.id}}">Editar Coleção {{collection.name}}</h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <form id="edit-room-form" method="post" action="{% url 'collection_update' collection.id %}">
                {% csrf_token %}
                <input type="hidden" name="type_id" value="{{ collection.id }}">
                <div class="mb-3">
                    <label for="id_name" class="form-label">Nome</label>
                    <input type="text" name="name" class="form-control" id="id_name" value="{{ collection.name }}" required>
                </div>
                <div class="mb-3">
                    <label for="id_description" class="form-label">Descrição</label>
                    
                    <textarea name="description" class="form-control" id="id_description" rows="3" required>{{ collection.description }}</textarea>
                </div>
                
                <div class="mb-3">
                    <label for="id_image" class="form-label">Imagem</label>
                    
                    {% if collection.image %}
                        <div class="mb-3">
                            <img src="{{ collection.image.url }}" class="img-fluid mb-2" alt="Imagem da coleção">
                        </div>
                    {% endif %}
                   
                    <input type="file" name="image" class="form-control" id="id_image">
                </div>
                <div class="modal-footer d-flex justify-content-center">
                    <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Cancelar</button>
                    <button type="submit" class="btn btn-primary">Salvar</button>
                </div>
            </form>
        </div>
    </div>
</div>